### ISSUE TITLE
Specify TypeScript as devDependency

### ISSUE THREAD

**Issue by aluanhaddad** [brhumphe/ModuleImportsTesting#1]
Add typescript to your project.json as a devDependency. Without knowing what version you are using there's little hope of an accurate reproduction of the issue. Even if you prefer to use a globally installed or npm linked version it's a good idea to add one to your project so that others can collaborate.

**Comment by brhumphe** [comment]
Good to know. I did it that way because that is how the React+Webpack tutorial does it. Fixed in latest commit.
